[package]
name = "server-actix-web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-http = "3.3.1"
actix-service = "2"
simd-json = "0.13"
simd-json-derive = "0.15.0"
bytes = "1"
actix-files = "0.6"
serde = { version = "1.0.219", features = ["derive"] }
